# .github/workflows/test-reusable-workflows.yml
name: Test Reusable Workflows (public)

on:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    name: Test SAST
    uses: checkr/.github/.github/workflows/sast.yml@main
    with:
      product: "Security"

  secrets:
    name: Test Secrets
    uses: checkr/.github/.github/workflows/secrets.yml@main
    with:
      product: "Security"

  dependencies:
    name: Test Dependencies
    uses: checkr/.github/.github/workflows/dependencies.yml@main
    with:
      product: "Security"

  iac:
    name: Test IaC
    uses: checkr/.github/.github/workflows/iac.yml@main
    with:
      product: "Security"
