name: Test Reusable Workflows (public)

on:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    name: Test SAST
    uses: checkr/workflows-public/.github/workflows/sast.yml@main
    
  secrets:
    name: Test Secrets
    uses: checkr/workflows-public/.github/workflows/secrets.yml@main
    
  dependencies:
    name: Test Dependencies
    uses: chckr/workflows-public/.github/workflows/dependencies.yml@main
    
  iac:
    name: Test IaC
    uses: checkr/workflows-public/.github/workflows/iac.yml@main

